// module.exports = {
//   extends: ['@commitlint/config-conventional'],
// }
export default {
  extends: ['@commitlint/config-conventional'],
  // https://commitlint.js.org/#/reference-rules
  rules: {
    'subject-case': [0], //subject大小写不做校验
    // 类型美剧, git提交type必须是以下类型
    'type-enum': [
      //当前验证的错误级别
      2,
      // 在什么情况下进行校验,always标识一直进行校验
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'revert',
        'chore',
      ],
    ],
  },

  prompt: {
    messages: {
      type: '选择要提交的类型',
      scope: '选择一个提交范围',
      customScope: '选择一个提交范围',
      subject: '填写简短精炼的变更描述 :\n',
      body: '填写更加详细的变更描述(可选)',
      breaking: '列举非兼容性的重大的变更(可选). 使用"|"换行 :\n',
      footerPrefixesSelect: '选择关联issue前缀(可选)',
      customFooterPrefix: '填写自定义issue前缀',
      footer: '列举关联issue(可选) 例如: #31, #I3244 :\n',
      generatingByAI: '正在通过AI生成你的提交简短描述...',
      generatedSelectByAI: '选择一个AI生成的简单描述...',
      confirmCommit: '是否确认提交?',
    },
    // prettier-ignore
    types: [
    { value: 'feat', name: '特性:     新增功能', emoji: ':sparkles:' },
    { value: 'fix', name: '修复:      修复bug', emoji: ':bug:' },
    { value: 'docs', name: 'docs:     文档变更', emoji: ':memo:' },
    { value: 'style', name: 'style:    代码格式(不影响代码逻辑)', emoji: ':lipstick:' },
    { value: 'refactor', name: 'refactor: 重构(既不增加feature,也不是bug修复)', emoji: ':recycle:' },
    { value: 'perf', name: 'perf:     性能优化', emoji: ':zap:' },
    { value: 'test', name: 'test:     添加测试' , emoji: ':white_check_mark:'},
    { value: 'build', name: 'build:    打包' , emoji: ':construction:'},
    { value: 'ci', name: 'ci:       修改持续集成配置', emoji: ':ferris_wheel:' },
    { value: 'revert', name: 'revert:   回退', emoji: ':rewind:' },
    { value: 'chore', name: 'chore:    构建过程或辅助工具的变更', emoji: ':hammer:' },
  ],
    useEmoji: true,
    emojiAlign: 'center',
    useAI: false,
    aiNumber: 1,
    themeColorCode: '',
    scopes: [],
    allowCustomScopes: true,
    allowEmptyScopes: true,
    customScopesAlign: 'bottom',
    customScopesAlias: 'custom',
    emptyScopesAlias: 'empty',
    upperCaseSubject: false,
    markBreakingChangeMode: false,
    allowBreakingChanges: ['feat', 'fix'],
    breaklineNumber: 100,
    breaklineChar: '|',
    skipQuestions: [],
    issuePrefixes: [
      { value: 'closed', name: 'closed: ISSUES has been processed' },
    ],
    customIssuePrefixAlign: 'top',
    emptyIssuePrefixAlias: 'skip',
    customIssuePrefixAlias: 'custom',
    allowCustomIssuePrefix: true,
    allowEmptyIssuePrefix: true,
    confirmColorize: true,
    maxHeaderLength: Infinity,
    maxSubjectLength: Infinity,
    minSubjectLength: 0,
    scopeOverrides: undefined,
    defaultBody: '',
    defaultIssues: '',
    defaultScope: '',
    defaultSubject: '',
  },
}
